server:
  protocol: http
  host: hesper.example.com
  port: 8080
  base_uri: '/'
app:
  default_actions:
    - index
    - show
    - create
    - update
    - delete
  image_extensions:
    - jpg
    - jpeg
    - gif
    - png
    - ico
