server:
  protocol: http
  host: hesper.example.com
  port: 8080
  base_uri: '/'
app:
  id: '[+-]?\d+'
  site_name: CELAENO
  default_actions:
    - show
    - new
    - edit
    - delete
    - index
  image_extensions:
    - jpg
    - jpeg
    - gif
    - png
    - ico
